extends: airbnb
parser: babel-eslint
plugins:
  - flowtype
env:
  browser: true
globals:
  ga: false
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
      FunctionDeclaration:
        parameters: first

  linebreak-style: off
  curly: off
  comma-dangle: off
  prefer-destructuring: off
  default-case: off
  function-paren-newline: off
  camelcase: off

  class-methods-use-this: off

  object-curly-spacing: off
  object-curly-newline: off

  no-lonely-if: off
  no-continue: off
  no-bitwise: off
  no-param-reassign: off
  no-use-before-define: off
  no-shadow: warn
  no-nested-ternary: off
  no-restricted-globals: off
  no-restricted-properties: off
  no-useless-escape: off

  react/jsx-indent:
    - error
    - 4
  react/jsx-indent-props:
    - error
    - 4
  react/jsx-closing-tag-location: off
  react/jsx-wrap-multilines: off
  react/jsx-tag-spacing: off
  react/jsx-filename-extension: off
  react/jsx-no-bind: off
  react/prop-types: off
  react/sort-comp: off

  import/no-named-as-default-member: off
  import/prefer-default-export: off

  # Accessibility - disabled for now
  jsx-a11y/alt-text: off
  jsx-a11y/click-events-have-key-events: off
  jsx-a11y/label-has-for: off
  jsx-a11y/media-has-caption: off
  jsx-a11y/no-autofocus: off
  jsx-a11y/no-noninteractive-element-interactions: off
  jsx-a11y/no-static-element-interactions: off

  # Ideally we want to have this enabled.
  # It causes many errors to fix, though
  no-mixed-operators: off
