export default {
    MUSIC: [
        { index: 0, file: 'data/MUSIC/LOGADPCM.mp3' },
        { index: 1, file: 'data/MUSIC/TADPCM1.mp3' },
        { index: 2, file: 'data/MUSIC/TADPCM2.mp3' },
        { index: 3, file: 'data/MUSIC/TADPCM3.mp3' },
        { index: 4, file: 'data/MUSIC/TADPCM4.mp3' },
        { index: 5, file: 'data/MUSIC/TADPCM5.mp3' },
        { index: 1, file: 'data/MUSIC/JADPCM01.mp3' },
        { index: 2, file: 'data/MUSIC/JADPCM02.mp3' },
        { index: 3, file: 'data/MUSIC/JADPCM03.mp3' },
        { index: 4, file: 'data/MUSIC/JADPCM04.mp3' },
        { index: 5, file: 'data/MUSIC/JADPCM05.mp3' },
        { index: 6, file: 'data/MUSIC/JADPCM06.mp3' },
        { index: 7, file: 'data/MUSIC/JADPCM07.mp3' },
        { index: 8, file: 'data/MUSIC/JADPCM08.mp3' },
        { index: 9, file: 'data/MUSIC/JADPCM09.mp3' },
        { index: 10, file: 'data/MUSIC/JADPCM10.mp3' },
        { index: 11, file: 'data/MUSIC/JADPCM11.mp3' },
        { index: 12, file: 'data/MUSIC/JADPCM12.mp3' },
        { index: 13, file: 'data/MUSIC/JADPCM13.mp3' },
        { index: 14, file: 'data/MUSIC/JADPCM14.mp3' },
        { index: 15, file: 'data/MUSIC/JADPCM15.mp3' },
        { index: 16, file: 'data/MUSIC/JADPCM16.mp3' },
        { index: 17, file: 'data/MUSIC/JADPCM17.mp3' },
        { index: 18, file: 'data/MUSIC/JADPCM18.mp3' },
    ]
}
