export default {
    MUSIC: [
        { index: 0, file: 'data/MUSIC/TADPCM1.mp4' },
        { index: 1, file: 'data/MUSIC/TADPCM2.mp4' },
        { index: 2, file: 'data/MUSIC/TADPCM3.mp4' },
        { index: 3, file: 'data/MUSIC/TADPCM4.mp4' },
        { index: 4, file: 'data/MUSIC/TADPCM5.mp4' },
        { index: 5, file: 'data/MUSIC/JADPCM01.mp4' },
        { index: 6, file: 'data/MUSIC/Track6.mp4' },
        { index: 7, file: 'data/MUSIC/JADPCM02.mp4' },
        { index: 8, file: 'data/MUSIC/JADPCM03.mp4' },
        { index: 9, file: 'data/MUSIC/JADPCM04.mp4' },
        { index: 10, file: 'data/MUSIC/JADPCM05.mp4' },
        { index: 11, file: 'data/MUSIC/JADPCM06.mp4' },
        { index: 12, file: 'data/MUSIC/JADPCM07.mp4' },
        { index: 13, file: 'data/MUSIC/JADPCM08.mp4' },
        { index: 14, file: 'data/MUSIC/JADPCM09.mp4' },
        { index: 15, file: 'data/MUSIC/JADPCM10.mp4' },
        { index: 16, file: 'data/MUSIC/JADPCM11.mp4' },
        { index: 17, file: 'data/MUSIC/JADPCM12.mp4' },
        { index: 18, file: 'data/MUSIC/JADPCM13.mp4' },
        { index: 19, file: 'data/MUSIC/JADPCM14.mp4' },
        { index: 20, file: 'data/MUSIC/JADPCM15.mp4' },
        { index: 21, file: 'data/MUSIC/JADPCM16.mp4' },
        { index: 22, file: 'data/MUSIC/JADPCM17.mp4' },
        { index: 23, file: 'data/MUSIC/JADPCM18.mp4' },
        { index: 24, file: 'data/MUSIC/LOGADPCM.mp4' },
    ]
};
