export default {
    LOGO: { file:'data/MUSIC/LOGADPCM.WAV' },
    MUSIC: [
        { index: 0, file:null },
        { index: 1, file:'data/MUSIC/TADPCM1.WAV' },
        { index: 2, file:'data/MUSIC/TADPCM2.WAV' },
        { index: 3, file:'data/MUSIC/TADPCM3.WAV' },
        { index: 4, file:'data/MUSIC/TADPCM4.WAV' },
        { index: 5, file:'data/MUSIC/TADPCM5.WAV' },
        { index: 1, file:'data/MUSIC/JADPCM01.WAV' },
        { index: 2, file:'data/MUSIC/JADPCM02.WAV' },
        { index: 3, file:'data/MUSIC/JADPCM03.WAV' },
        { index: 4, file:'data/MUSIC/JADPCM04.WAV' },
        { index: 5, file:'data/MUSIC/JADPCM05.WAV' },
        { index: 6, file:'data/MUSIC/JADPCM06.WAV' },
        { index: 7, file:'data/MUSIC/JADPCM07.WAV' },
        { index: 8, file:'data/MUSIC/JADPCM08.WAV' },
        { index: 9, file:'data/MUSIC/JADPCM09.WAV' },
        { index: 10, file:'data/MUSIC/JADPCM10.WAV' },
        { index: 11, file:'data/MUSIC/JADPCM11.WAV' },
        { index: 12, file:'data/MUSIC/JADPCM12.WAV' },
        { index: 13, file:'data/MUSIC/JADPCM13.WAV' },
        { index: 14, file:'data/MUSIC/JADPCM14.WAV' },
        { index: 15, file:'data/MUSIC/JADPCM15.mp3' },
        { index: 16, file:'data/MUSIC/JADPCM16.WAV' },
        { index: 17, file:'data/MUSIC/JADPCM17.WAV' },
        { index: 18, file:'data/MUSIC/JADPCM18.WAV' },
    ]
}
