/* eslint-disable key-spacing,no-multi-spaces */
export default {
    VIDEO: [
        { index: 0,  name: 'ASCENSEU',  file:'data/VIDEO/VIDEO01.mp4' },
        { index: 1,  name: 'ASRETOUR',  file:'data/VIDEO/VIDEO02.mp4' },
        { index: 2,  name: 'BALDINO',   file:'data/VIDEO/VIDEO03.mp4' },
        { index: 3,  name: 'BOAT1',     file:'data/VIDEO/VIDEO04.mp4' },
        { index: 4,  name: 'BOAT2',     file:'data/VIDEO/VIDEO05.mp4' },
        { index: 5,  name: 'BOAT3',     file:'data/VIDEO/VIDEO06.mp4' },
        { index: 6,  name: 'BOAT4',     file:'data/VIDEO/VIDEO07.mp4' },
        { index: 7,  name: 'BU',        file:'data/VIDEO/VIDEO08.mp4' },
        { index: 8,  name: 'CRASH',     file:'data/VIDEO/VIDEO09.mp4' },
        { index: 9,  name: 'DARK',      file:'data/VIDEO/VIDEO10.mp4' },
        { index: 10, name: 'DELUGE',    file:'data/VIDEO/VIDEO11.mp4' },
        { index: 11, name: 'END',       file:'data/VIDEO/VIDEO12.mp4' },
        { index: 12, name: 'END2',      file:'data/VIDEO/VIDEO13.mp4' },
        { index: 13, name: 'ENFA',      file:'data/VIDEO/VIDEO14.mp4' },
        { index: 14, name: 'FRAGMENT',  file:'data/VIDEO/VIDEO15.mp4' },
        { index: 15, name: 'GROTTE',    file:'data/VIDEO/VIDEO16.mp4' },
        { index: 16, name: 'INTRO',     file:'data/VIDEO/VIDEO17.mp4' },
        { index: 17, name: 'LUNES1',    file:'data/VIDEO/VIDEO18.mp4' },
        { index: 18, name: 'LUNES2',    file:'data/VIDEO/VIDEO19.mp4' },
        { index: 19, name: 'MONTCH',    file:'data/VIDEO/VIDEO20.mp4' },
        { index: 20, name: 'MOON',      file:'data/VIDEO/VIDEO21.mp4' },
        { index: 21, name: 'PASSEUR',   file:'data/VIDEO/VIDEO22.mp4' },
        { index: 22, name: 'PUB1',      file:'data/VIDEO/VIDEO23.mp4' },
        { index: 23, name: 'PUB2',      file:'data/VIDEO/VIDEO24.mp4' },
        { index: 24, name: 'PUB3',      file:'data/VIDEO/VIDEO25.mp4' },
        { index: 25, name: 'PUB4A6',    file:'data/VIDEO/VIDEO26.mp4' },
        { index: 26, name: 'SENDELL',   file:'data/VIDEO/VIDEO27.mp4' },
        { index: 27, name: 'SORT',      file:'data/VIDEO/VIDEO28.mp4' },
        { index: 28, name: 'SURSAUT',   file:'data/VIDEO/VIDEO29.mp4' },
        { index: 29, name: 'TAXI',      file:'data/VIDEO/VIDEO30.mp4' },
        { index: 30, name: 'TAXI_J',    file:'data/VIDEO/VIDEO31.mp4' },
        { index: 31, name: 'VOYAGEZ',   file:'data/VIDEO/VIDEO32.mp4' },
        { index: 32, name: 'ZEELP',     file:'data/VIDEO/VIDEO33.mp4' },
        { index: 33, name: 'BABY',      file:'data/VIDEO/VIDEO34.mp4' },
    ]
};
